name: c

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/c.yml"
      - "c/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/c.yml"
      - "c/**"

defaults:
  run:
    working-directory: c

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: ./make-all.sh test

  memcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: ./make-all.sh memcheck
