name: csharp

on:
  push:
    paths:
      - '.github/workflows/csharp.yml'
      - 'csharp/**'
    branches: [ master ]
  pull_request:
    paths:
      - '.github/workflows/csharp.yml'
      - 'csharp/**'
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build solution
      run: dotnet build csharp
    - name: Test
      run: dotnet test --no-build --verbosity normal csharp
