name: csharp

on:
  push:
    paths:
      - ".github/workflows/csharp.yml"
      - "csharp/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/csharp.yml"
      - "csharp/**"
    branches: [main]

defaults:
  run:
    working-directory: csharp

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0
      - name: Build solution
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
