name: elixir

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/elixir.yml"
      - "elixir/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/elixir.yml"
      - "elixir/**"

defaults:
  run:
    working-directory: elixir

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15.6"
          otp-version: "26"
      - name: Run tests
        run: ./test-all.sh
