name: fsharp

on:
  push:
    paths:
      - '.github/workflows/fsharp.yml'
      - 'fsharp/**'
    branches: [ master ]
  pull_request:
    paths:
      - '.github/workflows/fsharp.yml'
      - 'fsharp/**'
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore fsharp
    - name: Test
      run: dotnet test --no-restore --verbosity normal fsharp
