name: gleam

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/gleam.yml"
      - "gleam/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/gleam.yml"
      - "gleam/**"

defaults:
  run:
    working-directory: gleam

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "1.0.0"
          otp-version: "26"
      - name: Run tests
        run: ./test-all.sh
