name: Go

on:
  push:
    paths:
      - '.github/workflows/go.yml'
      - 'go/**'
    branches: [ master ]
  pull_request:
    paths:
      - '.github/workflows/go.yml'
      - 'go/**'
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: |
        for dir in $(find . -name go.mod -print0 | xargs -0 -n1 dirname | sort --unique); do
          (
              cd $dir
              go test -v .
          )
        done
