name: Go

on:
  push:
    paths:
      - ".github/workflows/go.yml"
      - "go/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/go.yml"
      - "go/**"
    branches: [main]

defaults:
  run:
    working-directory: go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: Run tests
        run: go list -f '{{.Dir}}' -m | xargs go test -v
