name: Java

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/java.yml"
      - "java/**"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/java.yml"
      - "java/**"

defaults:
  run:
    working-directory: java

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build with Gradle
        run: ./gradlew build
