name: kotlin

on:
  push:
    paths:
      - ".github/workflows/kotlin.yml"
      - "kotlin/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/kotlin.yml"
      - "kotlin/**"
    branches: [main]

defaults:
  run:
    working-directory: kotlin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: adopt
      - name: Build with Gradle
        run: ./gradlew build
