name: kotlin

on:
  push:
    paths:
      - ".github/workflows/kotlin.yml"
      - "kotlin/**"
    branches: [master]
  pull_request:
    paths:
      - ".github/workflows/kotlin.yml"
      - "kotlin/**"
    branches: [master]

defaults:
  run:
    working-directory: kotlin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Gradle
        run: ./gradlew build
