name: prolog

on:
  push:
    paths:
      - ".github/workflows/prolog.yml"
      - "prolog/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/prolog.yml"
      - "prolog/**"
    branches: [main]

defaults:
  run:
    working-directory: prolog

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-version: latest
      - uses: actions/checkout@v5
      - name: Run tests for all exercises
        run: ./test-all.sh
