name: ruby

on:
  push:
    paths:
      - ".github/workflows/ruby.yml"
      - "ruby/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/ruby.yml"
      - "ruby/**"
    branches: [main]

defaults:
  run:
    working-directory: ruby

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Run tests
        run: rake test
