name: rust

on:
  push:
    paths:
      - ".github/workflows/rust.yml"
      - "rust/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/rust.yml"
      - "rust/**"
    branches: [main]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: rust

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run tests
        run: cargo test
