name: scala

on:
  push:
    paths:
      - ".github/workflows/scala.yml"
      - "scala/**"
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/scala.yml"
      - "scala/**"
    branches: [main]

defaults:
  run:
    working-directory: scala

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: adopt
      - name: Run tests
        run: sbt test
