name: scala

on:
  push:
    paths: 
      - ".github/workflows/scala.yml"
      - "scala/**"
    branches: [ master ]
  pull_request:
    paths: 
      - ".github/workflows/scala.yml"
      - "scala/**"
    branches: [ master ]

defaults:
  run:
    working-directory: scala

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: sbt test
