name: Swift

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/swift.yml"
      - "swift/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/swift.yml"
      - "swift/**"

defaults:
  run:
    working-directory: swift

env:
  RUNALL: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:5.8
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test
