name: Swift

on:
  pull_request:
  push:
    branches: [master]
    paths:
      - ".github/workflows/swift.yml"
      - "swift/**"

defaults:
  run:
    working-directory: swift

env:
  RUNALL: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:5.8
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: swift test
