# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: typescript

on:
  push:
    paths: 
      - '.github/workflows/typescript.yml'
      - 'typescript/**'
    branches: [ master ]
  pull_request:
    paths: 
      - '.github/workflows/typescript.yml'
      - 'typescript/**'
    branches: [ master ]

defaults:
  run:
    working-directory: typescript

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn workspaces run test
